### ISSUE TITLE
prelim results - bimodality of trait distributions

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/magnifica#10]
Seems most traits have some sort of bimodality in distribution. As an example, see zooid height:

![zooid height](https://github.com/megbalk/magnifica/blob/main/Results/zooid_height.png)

Bimodality is only seen in three formations: Waipurpu, NKBS, Upper Kai-Iwi
![by formation](https://github.com/megbalk/magnifica/blob/main/Results/zooid_height_by_formation.png)

Possibly due to image quality? Will need to see boxes and output images that relate to output_21Apr2023_Stegniator.csv.

It seems the first mode ends around 300 pixels, which encompass 95 images (out of 891 images total).

**Comment by agporto** [comment]
most likely the result of predictions errors + magnification differences.

**Comment by meghalithic** [comment]
I will check magnification first, then may need help looking at prediction errors.

**Comment by meghalithic** [comment]
not driven by magnification

![magnification](https://github.com/megbalk/magnifica/blob/main/Results/zooid_height_by_magnification.png)

**Comment by meghalithic** [comment]
deselecting certain zooids did not help...

**Comment by meghalithic** [comment]
determined it may be a cryptic species and created a new repo for this [small zooids](https://github.com/megbalk/small_zooids)
