### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/magnifica#11]
DATA WRANGLING:
- [x] compare AP metadata file with lab metadata file and images in JPG
- [x] create subset of images to run through Steginator
- [x] add in scale

ANALYSES:
- [x] sum(diag(P)) v sum(diag(G)) (sum of diagonal is like size of the matrix)
- [x] sum(diag(P)) v time
- [x] sum(diag(P)) v change in angle
- [x] conditional evolvability v time, size of matrix, change in angle

**Comment by megbalk** [comment]
Metadata tasks:

- [ ] compare .tif info to information inside of associated .txt file for Stegino images
- [ ] compare corrected Stegino images to image metadata
- [ ] compare file list of Stegino image to file list of images from lab computer

**Comment by megbalk** [comment]
Steginator tasks:

- [ ] create subset of images to run through Steginator

Maybe trim dataset based off AV, Magnification, and BSE

**Comment by megbalk** [comment]
random notes to self:
Check S, P, F

Make note of weird 99 _1_1

Add lower case v to protocol
Add 4 numbers, including leading 0s


Fill in missing new file names

Add other stuff to protocol

Standardize specimen number and file name

# standardize "v" in AV to be lowercase
# standardize four numbers
# standardize everything before ext is separated by "_"
# standardize all AV have 2 digits
# standardize all fileName to have BSE

**Comment by meghalithic** [comment]
- [x] investigate largest operculum widths and zooid heights

operculum width at midline:
boxID = 290_1913_523_687; imageName = 806_CV_2_10v_x30_BSE
boxID = 927_2047_495_737; imageName = 768_CC_2_15v_x30_BSE 

zooid height:
boxID = 301_1136_705_1252; imageName = 511_CV_1_15v_x30_BSE
boxID = 21_769_409_746; imageName = 084_CV_2_10v_x30_BSE

**Comment by meghalithic** [comment]
- [x] investigate images that make up the [small bimodal hump](https://github.com/megbalk/magnifica/blob/main/Results/small_bimodal_hump.csv)
