### ISSUE TITLE
difference between lab computer images and zip file images

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/magnifica#13]
The only difference was that the lab computer has the image "MHR.713.BLEED.582.tif". I am unsure what this image is or of? @klvoje any ideas what the prefix MHR is?

**Comment by klvoje** [comment]
Hi Meghan,


MHR is short for Mali Hamre Ramsfjell. I checked the image "MHR.713.BLEED.582.tif" and it is not a Steginoporella.


Best,

Kjetil

________________________________
From: Meghan Balk ***@***.***>
Sent: 04 April 2023 11:54:43
To: megbalk/magnifica
Cc: Kjetil Lysne Voje; Mention
Subject: [megbalk/magnifica] difference between lab computer images and zip file images (Issue #13)


The only difference was that the lab computer has the image "MHR.713.BLEED.582.tif". I am unsure what this image is or of? @klvoje<https://github.com/klvoje> any ideas what the prefix MHR is?
