### ISSUE TITLE
traits in bryozoans

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/magnifica#2]
From discussion with Carolann:

- in the literature, we'll find traits on maximum width of operculum and maximum height of zooid at the center lines
- suggested that right and left lengths of the cryptocyst may not be that biologically informative
- suggested looking at proportions of b-zooids (both in relative size and in relative number)
- suggested taking base and mid-width measurements
- suggested that maximum height is from landmark 4, not 2
- said that the distance between 20 to 21 is the base of the operculum, not condyles
- suggested also taking a measurement of polypide tube width (between landmarks 5 and 6) as that varies between species
- suggested we don't take averages as there may be asymmetry that is interesting

**Comment by agporto** [comment]
@megbalk just fyi, Steginoporella magnifica does not have b-zooids (at least, as far as I know).  other stegs species have plenty

**Comment by meghalithic** [comment]
@agporto thanks! I think Carolann was suggesting that perhaps we look at the change from only zooids to b-zooids to aviculara for later analyses.
